export enum AppErrorCode {
  SUBSCRIPTION_NOT_FOUND = 'SUBSCRIPTION_NOT_FOUND',
  CANNOT_SUBSCRIBE_YOURSELF = 'CANNOT_SUBSCRIBE_YOURSELF',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  LIKE_NOT_FOUND = 'LIKE_NOT_FOUND',
  POST_NOT_FOUND = 'POST_NOT_FOUND',
  COMMENT_NOT_FOUND = 'COMMENT_NOT_FOUND',
}
